export {default as HomePage} from "./home-page"
export {default as ProductsPage} from "./products"
export {default as ProfilePage} from "./profile-page"
export {default as ProductDetailsPage} from "./product-details"
export {default as NotFoundPage} from "./not-found"
export {default as ResetPassword} from "./reset-password"
export {default as LikedProducts} from "./liked-products"
export {default as VerifyOtp} from "./verify-otp"