export {default as HeaderTop} from "./home/header/header-top"
export {default as Header} from "./home/header/header"
export {default as HeaderCategories} from "./home/header/header-categoryies"
export {default as HeaderSlider} from "./home/header/header-slider"
export {default as Brands} from "./home/brands/brands"
export {default as FilterSection} from "./products/filter-section"
export {default as CardsSection} from "./products/cards-section"
export {default as Footer} from "./home/footer/footer"
export {default as CategoryProducts} from "./home/category/categories"
export {default as ReletedProductsData} from "./home/popular-products/popular-products"
export {default as AksiyaProducts} from "./home/popular-products/aksiya-products"
export {default as LastSeenProducts} from "./home/popular-products/last-seen-products"
export {default as ProductDetails} from "./products/product-detials/product-details"
export {default as HeadphoneSection} from "./home/headphone/headphone"
export {default as ProfileSection} from './profile/profile'
export {default as AccountDetails} from './profile/account-details'
export {default as Address} from './profile/address'
export {default as MyProducts} from './profile/my-products'
export {default as Profile} from './profile/profile'
export {default as Wishlist} from './profile/wishlist'
export {default as TrackOrder} from './profile/track-order'
export {default as SetNewPassword} from './profile/set-new-password'